spring:
  application:
    name: ai-agent
  profiles:
    active: local
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b

#    dashscope:
#      api-key: local 中
#      chat:
#        options:
#          model: qwen-plus
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536 # 如果不设置，默认使用 Embedding 维度
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
    # 用于在本地测试环境下禁用 pgvector
    app:
      pgvector:
        enabled: false  #在需要连 PG 的环境才打开。 true 开or false 关

# local 中
#    datasource:
#      url: jdbc:
#      username:
#      password:



server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xinwei.aiagent.controller
# knife4j ????????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug

# searchApi
#search-api:
#  api-key: local 中